title : Chemistry At Andover
tagline : Learn chemistry in a fun and engaging way
description : We present chemistry in fun blog posts, memes, and textbook that we have written
url : https://chemistryatandover.github.io/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from

markdown: kramdown
kramdown:
    math_engine: katex
    
permalink: /:title

author:
  name: Andover Chem Club
social:
  name: Andover Chem Club
  links:
    - https://github.com/ChemistryAtAndover

